version: "2"

services:
    nginx:
        restart: unless-stopped
        container_name: ${PROJECT_NAME}_nginx
        build: ./nginx
        ports: 
            - "80:80"
        volumes:
            - ./nginx/conf:/etc/nginx/conf.d
            - ${PROJECTS_PATH}:/var/www

    php-fpm:
        restart: unless-stopped
        container_name: ${PROJECT_NAME}_php-fpm
        build: ./php-fpm
        volumes:
           - ${PROJECTS_PATH}:/var/www

    mysql:
        restart: unless-stopped
        container_name: ${PROJECT_NAME}_mysql
        platform: linux/x86_64
        build: ./mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - ./database/mysql:/var/lib/mysql
            - ./database/dump:/dump